#!/bin/bash
# init

. /usr/local/bin/editscript

scriptname="$(realpath $0)"
dev="/dev/sr0"
ripdir="/dev/shm/cache/"
red="$(tput setaf 1)"
bold="$(tput bold)"
tput0="$(tput sgr0)"
force="false"

getdev(){
 [[ "${0##*/}" = cdrip ]] && dev="/dev/sr0"
 [[ "${0##*/}" = cdrip1 ]] && dev="/dev/sr1"
}

cdcheck(){
 while true; do
    cdinfo=$(setcd -i "$dev")
    case "$cdinfo" in
        *'Disc found'*)
            printf '\nDrive closed and cd present!\n\n'
            break
            ;;
        *'not ready'*)
            printf '\n(waiting for drive to be ready)\n\n' >&2
            /usr/bin/sleep 3
            ;;
        *'is open'*)
            printf '\n(drive is open)\n' >&2
            eject -t "$dev"
            /usr/bin/sleep 5
            ;;
        *)
            printf 'Confused by setcd -i, bailing out:\n%s\n' "$cdinfo" >&2
            exit 1
    esac
 done
}


checkdep(){
  if "$force"; then
    sudo apt -y install cdparanoia setcd flac cd-discid
  fi
 { ! command -v cdparanoia || ! command -v setcd || ! command -v cd-discid || ! command -v flac ; } >/dev/null &&
 printf 'The following dependencies are required to run cdrip: cdparanoia, setcd, flac, and cd-discid; picard is called at the end but not necessary\n' &&
 printf 'Check the dependencies and try again or run with -y to call apt...\n' &&
 exit 1
}

#[[ "$1" = @(edit|e|-e) ]] && editscript

[[ "$1" = -y ]] && force=true && shift

[[ "$1" = -d ]] && dev="$2" && shift 2

[[ -d "$ripdir" ]] || mkdir -p "$ripdir"

checkdep "$force"

getdev

echo "Closing CD tray (if open)..."
eject -t "$dev"

echo
echo "Checking for CD ..."

cdcheck

cdparanoia -Q -d "$dev"

#requires cd-discid
tracks="$(cd-discid $dev)"; tracks="${tracks#* }"; tracks="${tracks%% *}"
printf \\n\\n
[[ "$1" ]] && name="$1" || read -p "File name?  " name
#echo "There are $tracks tracks.  The files will be named "$name"-{01.."$tracks"}.flac in "$ripdir""$name""
printf '\nThere are %s tracks.  The files will be named "%s-{01..%s}.flac" in "%s%s"' "$tracks" "$name" "$tracks" "$ripdir" "$name"

mkdirout="$(mkdir "$ripdir$name" 2>&1)"

printf '\n%s%s%s%s' "${mkdirout:+"$bold"}" "${mkdirout:+"$red"}" "${mkdirout:-"Directory created"}" "$tput0"

cd "$ripdir$name"
printf \\nPWD\:\ %s\\n\\n "$PWD"
ls -alF
printf \\n\\n
! "$force" && pause 'Press [Enter] key to continue...'
printf \\n\\n

cdparanoia -B -d "$dev"

for ((i=1; i<=tracks; i++)); do
  printf -v trackno %02d "$i"      #defines $trackno variable
  if [[ -f "track$trackno.cdda.wav" ]]; then
    flac -8 "track$trackno.cdda.wav" -o "$name-$trackno.flac" && rm "track$trackno.cdda.wav"
  else
    printf 'Track %s: file track%s.cdda.wav not found\n' "$trackno" "$trackno"
    if "$force"; then
      printf 'Failed to find all tracks on cd; investigate.\n(exit 1)'
      exit 1
    fi
  fi
done


[[ -f "track00.cdda.wav" ]] && rm track00.cdda.wav

command -v picard && picard . -e cluster -e scan clustered -e LOOKUP_CD "$dev" 2>/dev/null &

{ sleep 10s && eject "$dev" ; }&

