#!/bin/bash
# init

. /usr/local/bin/editscript

scriptname="$(realpath $0)"
dev="/dev/sr0"
ripdir="/dev/shm/cache"
red="$(tput setaf 1)"
yellow="$(tput setaf 3)"
white="$(tput setaf 7)"
bold="$(tput bold)"
tput0="$(tput sgr0)"

getdev(){
 [[ "${0##*/}" = cdrip ]] && dev="/dev/sr0"
 [[ "${0##*/}" = cdrip1 ]] && dev="/dev/sr1"
}

cdcheck(){
  while true; do
    cdinfo=$(setcd -i "$dev")
    case "$cdinfo" in
        *'Disc found'*)
            printf '\nDrive closed and cd present!\n\n'
            break
            ;;
        *'not ready'*)
            printf '\n(waiting for drive to be ready)\n\n' >&2
            /usr/bin/sleep 3
            ;;
        *'is open'*)
            printf '\n(drive is open)\n' >&2
            eject -t "$dev"
            /usr/bin/sleep 5
            ;;
        *)
            printf 'Confused by setcd -i, bailing out:\n%s\n' "$cdinfo" >&2
            exit 1
    esac
 done
}


checkdep(){
  if "$force"; then
    sudo apt -y install cdparanoia setcd flac cd-discid
  fi
 { ! command -v cdparanoia || ! command -v setcd || ! command -v cd-discid || ! command -v flac ; } >/dev/null &&
 printf 'The following dependencies are required to run cdrip: cdparanoia, setcd, flac, and cd-discid; picard is called at the end but not necessary\n' &&
 printf 'Check the dependencies and try again or run with -y to call apt...\n' &&
 exit 1
}

helpout(){
  getdev
  printf 'Usage: %s -y -d <device> <album name>' "${0##*/}"
  printf '-y to force yes to all prompts\n'
  printf '-d <device> to specify a different device than %s' "$dev"
  printf '-h|--help to display this help message and exit'
  exit 0
}

#[[ "$1" = @(edit|e|-e) ]] && editscript

while (( $# > 0 )); do
  [[ "$1" = -y ]] && force=true && shift
  [[ "$1" = -d ]] && dev="$2" && shift 2
  [[ "$1" =~ ^-(h|-help)$ ]] && helpout && exit 1
  [[ "$@" ]] && name="$@" && shift "$#"
done

if [[ ! -d "$ripdir" ]]; then
  mkdir -p "$ripdir"
  ec="$?"
  (( ec )) && { printf 'Failed to create parent rip directory: "%s".\n(exit 1)' "$ripdir"; exit 1; }
fi

checkdep "${force:=false}"

getdev

ckdevout="$(setcd -i "$dev")"
ec1="$?"

if [[ "$ckdevout" = *"is open"* ]]; then
  printf 'Closing CD tray...\n'
  ejectout="$(eject -t "$dev" 2>&1)"
  ec2="$?"
elif [[ "$ckdevout" = "Can't open device: No such file or directory" || ! -e "$dev" ]]; then
  printf '[%s%sERROR%s] Device "%s" not found.\nCheck the device path and try again.\n' \
    "$bold" "$red" "$tput0" "$dev"
  exit 1
fi

if (( ec1 || ec2 )); then
  if [[ "$ejectout" = 'eject: CD-ROM tray close command failed: No such file or directory' ]]; then
    printf '[%s%sWARN%s] eject reported CD-ROM tray close command failed.\n\n%s%sManually close while continuing...%s\n' \
      "$bold" "$yellow" "$tput0" "$bold" "$red" "$tput0"
  elif [[ "$ejectout" = 'eject: '*': not found mountpoint or device with the given name: command not found' ]]; then
    printf '[%s%sERROR%s] eject did not recognize the CD-ROM device "%s".\nThis likely means it does not exist.\nCheck the device and try again. (exit 1)\n' \
      "$bold" "$red" "$tput0" "$dev"
    exit 1
  else
    printf '[%s%sWARN%s] eject/setcd reported an unexpected error:\n%s\n%s\nAttempting to continue...\n' \
      "$bold" "$yellow" "$tput0" "$ckdevout" "$ejectout"
  fi
fi

printf '\nChecking for CD ...\n'

cdcheck

cdparanoia -Q -d "$dev"

tracks="$(cd-discid $dev)"; tracks="${tracks#* }"; tracks="${tracks%% *}"
printf \\n
[[ "$name" ]] || read -p "File name? " name

outdir="$ripdir/$name"
mkdirout="$(mkdir "$outdir" 2>&1)"
ec="$?"
cd "$outdir"
#db printf \\nPWD\:\ %s\\n\\n "$PWD"

# todo: remove -p above and confirm using an existing directory instead of assuming overwrite.
if (( ec )); then
  if [[ "$mkdirout" = "mkdir: cannot create directory ‘$outdir’: File exists" ]]; then
    printf '%s[%sWARN%s] Output directory "%s%s%s" exits, review below!%s\n' "$bold" "$yellow" "$white" "$yellow" "$outdir" "$white" "$tput0"
    outdirexit=true
    ls -alF --color=always
  else
    printf '\n[%s%sERROR%s] mkdir resulted in non-zero exit code:\nexit %s: %s\n(exit 1)\n' "$red" "$bold" "$tput0" "$ec" "$mkdirout"
    exit 1
  fi
else
  printf '%sDirectory %s"%s"%s created.%s' "$bold" "$yellow" "$outdir" "$white" "$tput0"
fi

printf '\n\nThe %s tracks will be named "%s%s-{01..%s}.flac%s" in "%s%s%s"\n' "$tracks" "$yellow$bold" "$name" "$tracks" "$tput0" "$yellow$bold" "$outdir" "$tput0"


#if "${outdirexit:=false}"; then
#  printf '\n%s%sOutput directory exists; contents will be overwritten!%s\n' "$bold" "$yellow" "$tput0"
##  command -v eza &>/dev/null && eza -l --color=always || ls -alF --color=always
#fi

printf \\n
! "$force" && pause 'Press [Enter] key to continue...'
printf \\n\\n

cdparanoia -B -d "$dev"

for ((i=1; i<=tracks; i++)); do
  printf -v trackno %02d "$i"      #defines $trackno variable
  if [[ -f "track$trackno.cdda.wav" ]]; then
    flac -8 "track$trackno.cdda.wav" -o "$name-$trackno.flac" && rm "track$trackno.cdda.wav"
  else
    printf 'Track %s: file track%s.cdda.wav not found\n' "$trackno" "$trackno"
    if "$force"; then
      printf 'Failed to find all tracks on cd; investigate.\n(exit 1)'
      exit 1
    fi
  fi
done


[[ -f "track00.cdda.wav" ]] && rm track00.cdda.wav

command -v picard && picard . -e cluster -e scan clustered -e LOOKUP_CD "$dev" 2>/dev/null &

{ sleep 10s && eject "$dev" ; }&

